# Generated by Django 3.2.23 on 2024-09-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon_v2', '0016_typesprites'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveNameChangelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movenamechangelog', to='pokemon_v2.generation')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movenamechangelog_language', to='pokemon_v2.language')),
                ('move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movenamechangelog', to='pokemon_v2.move')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movenamechangelog', to='pokemon_v2.type')),
            ],
        ),
    ]
