# Generated by Django 3.2.23 on 2024-09-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonmoveavailability',
            name='forms',
            field=models.ManyToManyField(blank=True, related_name='pokemonmoveavailability', to='middleware.PokemonMoveAvailability'),
        ),
    ]
